language: node_js
node_js:
- 7.3.0
notifications:
  slack:
    secure: rGWf+VLMXJrfGZvQmJ5kyrOIpOXll8YI8cxRCNi93OhBXU+Mc+BQ7e9ib3p7KrjALfZ9hN8uA1BwK7Hwx7r2My8AfDDkMkjvmHqP/Dv038GMFoR282LuYU+9F/nm99lJWI4KFi7/IeJ/oTR+UQB+LXNaiak0cFVOE8oi1JLoVWXiETKpEZUIgn7p0F9hetmXCFIiutlOUlEkfScu2zL7kHJMYNPndsRCgAcbCD3PfUsxpVumWVm3xLEWHP73uYoYB5jPehloWGg8CiNBFDIOogPbvIgA4m6ptroVob8ZjEVsRZ9qdVIbYqb4WXD4m62viI2MGcuBtd+OPC7oXD4C+LAcO9A6XFmVFDkxq9j9VxY6+9dR4m3YBCdiMcRui+XPHfi4DXY+m6Hi5miRZ2uRg/WH6YSQBv2qdSOOZ4PSmW0plrAQAcvwPKNeuoj/iKF5fe/SHohuUUU7LPOSiUVCT7x5DV+wPvseNoe0VL12Ygoy+fxk88jXnzBErGnktYSKHE5azzkzZPeXEv8aD4DB9C1M5QjrLi2Eh3xLCYq8MwO2SmKdJfFbtgv6jibrvnQHGT1bW0hgCzcUDbrISdAjCvoe95UCUOhnXGl0iKs96pLSy+WCKHdh/j1MVPsiSjm/WPWmnPTEteGYuthiCGWiWey8AZKpjgWTlP/ECsIUExE=
